### ISSUE TITLE
liveness vs readiness endpoints switched?

### ISSUE THREAD

**Issue by mtaron** [guidance-ai/llgtrt#31]
The implementation of the [liveness and readiness health checks](https://github.com/guidance-ai/llgtrt/blob/a74cbb55b2e96db8c1c5f7f73c419dfc06ec0411/llgtrt/src/routes/health_check.rs#L18) are swapped based on my expectations from using [Kubernetes liveness and readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/). 

I expect liveness to mean "are you alive?" and when it fails enough times (configurable), Kubernetes will restart the container. This matches the current "/v1/health/ready" endpoint which just returns.

Readiness on the other hand means "can you serve traffic right now?". If it fails, Kubernetes will avoid routing traffic to that container, but won't restart it. This matches the implementation of "/v1/health/live" which is checking whether a request can be enqueued.

This isn't a blocker or anything since you can configure the route for the probes; just thought I'd mention it.

```yaml
# wait for the model to respond before considering the container started. 
# 10 minute timeout
startupProbe:
  httpGet:
    path: /v1/health/model
    port: http
  failureThreshold: 600
  periodSeconds: 10
# restart the container if this fails
livenessProbe:
  httpGet:
    path: /v1/health/ready
    port: http
  periodSeconds: 10
# don't serve traffic if this fails
readinessProbe:
  httpGet:
    path: /v1/health/live
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
```
